5 create consult form on the landing page
first-care-solutions/ed-greenline pull request #10
Opened 2022-04-14 05:57 UTC by tmanmoseri

please review and comment on the codes

2022-04-14 13:15 UTC, tmanmoseri reviewed
Successfully Added the datepicker popup button

2022-04-20 06:47 UTC, jakesfcoetz requested changes
Thank you Mogale.
Things are looking up. Great work.
Here are just a few comments from my side to take note of and some changes that need to be implemented.

2022-04-20 06:47 UTC, jakesfcoetz commented on src/app/pages/landing-page/landing-page.component.ts
> +  getDate(event) {
```suggestion

  getDate(event) {
```

2022-04-20 06:47 UTC, jakesfcoetz commented on src/app/pages/landing-page/landing-page.component.ts
> +    let date = new Date(event.target.value).toISOString().substring(0, 10);
The `date` variable is defined but never used.

Since you are working with dates. This is a great opportunity to introduce you to `dayjs`. It is a package that we use throughout all of our apps. You don't need to implement it in this branch, but you are welcome to read up on it. It is the only date management app we currently use.

https://day.js.org/docs/en/installation/node-js

2022-04-20 06:47 UTC, jakesfcoetz commented on src/app/pages/landing-page/landing-page.component.ts
> +import { Validators, FormBuilder, FormGroup, FormControl } from '@angular/forms';
Please ensure that all unused imports are removed from the list.

2022-04-20 06:47 UTC, jakesfcoetz commented on src/app/pages/landing-page/landing-page.component.html
> +          <ion-row radio-group>
Wonderful use of `grid`, please refer to the previous comment on adding `<ion-row>` inside of `<ion-grid>`

2022-04-20 06:47 UTC, jakesfcoetz commented on src/app/pages/landing-page/landing-page.component.html
> +              <ion-radio value="0"></ion-radio>
Since this type of radio button form view is something we use regularly, please look at an example on the ionic docs under `<ion-item`> where the item contains the radio buttons. This greatly improves the user experience and layout design, especially on mobile designs.

2022-04-20 06:47 UTC, jakesfcoetz commented on src/app/pages/landing-page/landing-page.component.html
> +      <span class="error ion-padding" *ngIf="isSubmitted && errorControl['idNumber'].errors?.['required']"> IdNumber is required. </span>
Please taken note of  a few error spans that are not displaying correctly.

2022-04-20 06:47 UTC, jakesfcoetz commented on src/app/pages/landing-page/landing-page.component.html
> +      <span class="error ion-padding" *ngIf="isSubmitted && errorControl['cellNumber'].errors?.['required']"> CellNumber is required. </span>
Another great way of form validation feedback is to use the `formControl.dirty` property to only show the error once a user has started to interact with the item. Please look into this as this greatly improves the user feedback experience by giving real-time feedback.

2022-04-20 06:47 UTC, jakesfcoetz commented on src/app/pages/landing-page/landing-page.component.ts
> +      this.router.navigate(['/pages/virtual-room']);
Everything after a return statement is not executed since it ends the execution of the method. Please correct this to the desired flow of events.

2022-04-20 07:52 UTC, tmanmoseri commented on src/app/app-routing.module.ts
> +    component: LandingPageComponent
resolved my ommiting pathMatch on all paths.

2022-04-20 08:08 UTC, tmanmoseri commented on src/app/app.module.ts
> +import { ScrollingModule } from '@angular/cdk/scrolling';
i removed the scrolling module and the virtual room component

2022-04-20 09:41 UTC, tmanmoseri commented on src/app/pages/landing-page/landing-page.component.ts
> +      this.router.navigate(['/pages/virtual-room']);
movede the router statement above the return line.

2022-04-20 11:59 UTC, tmanmoseri commented on src/app/pages/landing-page/landing-page.component.html
> +<ion-header>
added ionic content tag

2022-04-20 12:53 UTC, tmanmoseri commented on src/app/pages/landing-page/landing-page.component.html
> +      <span class="error ion-padding" *ngIf="isSubmitted && errorControl['idNumber'].errors?.['required']"> IdNumber is required. </span>
All buttons display errors accordingly

2022-04-20 13:15 UTC, tmanmoseri commented on src/app/pages/landing-page/landing-page.component.html
> +          <ion-row radio-group>
I have looked into few grid options and have also added grid to the ion-row tabs

2022-04-20 13:18 UTC, tmanmoseri commented on src/app/pages/landing-page/landing-page.component.html
> +          <ion-datetime presentation="date" [(ngModel)]="defaultDate" [ngModelOptions]="{ standalone: true }" locale="sl-SI"></ion-datetime>
I have changed calender language and have aligned calender popup to fit to screen at the bottom

2022-04-20 13:52 UTC, tmanmoseri commented on src/app/pages/landing-page/landing-page.component.html
> +              <ion-radio value="0"></ion-radio>
i have looked into ionic doc under <ion-item>, is there a pecific pattern need to reconsider and incoporate into my codes, please advise

2022-04-21 12:11 UTC, jakesfcoetz commented on src/app/pages/landing-page/landing-page.component.ts
> +  getDate(event) {
Please see that you either complete the requested changes or comment as to why they were ignored.

The purpose of this method is also very vague since it is never called nor does it perform any function. When committing code for review please ensure that the code is cleaned-up and that you are satisfied with having this code deployed.

2022-04-21 12:18 UTC, jakesfcoetz commented on src/app/pages/landing-page/landing-page.component.html
> +            <ion-row radio-group>
Thank you for adding the `ion-grid`. I would however like to know what is the purpose of the `radio-group` attribute in the `ion-row` since it seems to have no effect?

2022-04-21 12:18 UTC, jakesfcoetz commented on src/app/pages/landing-page/landing-page.component.html
> +              <ion-radio value="0"></ion-radio>
The ionic documentation for `ion-radio` shows a good example of radio buttons inside an `ion-item`, please refer to:
https://ionicframework.com/docs/api/radio

2022-04-21 12:28 UTC, jakesfcoetz requested changes
Thank you @tmanmoseri for these changes. There are however a few comments from the previous review that were not considered and a few further requests. Please see to them and ensure that the code submitted for review is cleaned up as this will greatly impact the efficiency of the reviews and improve the overall code base integrity.

2022-04-21 12:28 UTC, jakesfcoetz commented on src/app/pages/landing-page/landing-page.component.ts
> +  async presentModal() {
Please clean up your code before submitting it for review. Unnecessary code or imports or even methods, clutter up the code an brings the entire code base's integrity into question.

2022-04-21 12:28 UTC, jakesfcoetz commented on src/app/pages/landing-page/landing-page.component.ts
> +    this.ionicForm.reset();
This statement falls outside the scope of this method and is therefore never executed. VS Code also shows it as "grayed out".

2022-04-21 12:28 UTC, jakesfcoetz commented on src/app/pages/landing-page/landing-page.component.ts
> +    return this.ionicForm.controls;
The content of this method does not quite match the name. It is always good practice to choose method and variable names that describe their purpose.

2022-04-22 06:36 UTC, tmanmoseri commented on src/app/pages/landing-page/landing-page.component.html
> +              <ion-radio value="0"></ion-radio>
I have managed to implement ion-radio inside ion-item

2022-04-22 06:37 UTC, tmanmoseri commented on src/app/pages/landing-page/landing-page.component.html
> +            <ion-row radio-group>
the radio-group within ion-row was redundant and i have removed it. Thanks

2022-04-22 06:43 UTC, tmanmoseri commented on src/app/pages/landing-page/landing-page.component.ts
> +    this.ionicForm.reset();
That i have used for testing purpose. i will comment unused codes or remove them completely nextime before commiting

2022-04-22 06:44 UTC, tmanmoseri commented on src/app/pages/landing-page/landing-page.component.ts
> +  async presentModal() {
Thanks @jakesfcoetz. I will thoroughly clean my codes before commiting.

2022-04-22 06:54 UTC, tmanmoseri commented on src/app/pages/landing-page/landing-page.component.scss
> +  left: 0 !important;
I have implemented <ion-input type="date" > and it seems to work perfect, thanks.

2022-04-22 08:24 UTC, tmanmoseri commented on src/app/pages/landing-page/landing-page.component.ts
> +    return this.ionicForm.controls;
I have managed to rename the method to a more meaningful name

2022-04-22 09:55 UTC, jakesfcoetz requested changes
Thank you Mogale for these changes, creeping closer to the goal. There are a few requests for your consideration, some of them new and some from previous reviews. Please see to these changes and ensure that you comply with the requests of the original issue:

1. On the form, indicate which fields are required for the user to complete (Here I recommend adding an '*' to the required fields.
2. Create a user form in an Ionic Card that has the below fields (Please add the requested card)

2022-04-22 09:55 UTC, jakesfcoetz commented on src/app/pages/landing-page/landing-page.component.html
> +              <ion-col>
As per the previous review, please add an `ngFor` directive to reduce the amount of code required to create these `ion-col` elements.

2022-04-22 09:55 UTC, jakesfcoetz commented on src/app/pages/landing-page/landing-page.component.html
> +    <form [formGroup]="ionicForm" (ngSubmit)="submitForm()" novalidate>
As per the previous review, could you please elaborate on the purpose of `novalidate`?

2022-04-22 09:55 UTC, jakesfcoetz commented on src/app/pages/landing-page/landing-page.component.html
> +                <ion-radio value="mr"></ion-radio>
As per the previous review, please display these `ion-radio` buttons inside an `ion-item` as shown in the Ionic documentation examples.

2022-04-22 09:55 UTC, jakesfcoetz commented on src/app/pages/landing-page/landing-page.component.html
> +          Identification Number should be min 10 chars long.
Please ensure that the validation message corresponds to the validation set on the form. RSA ID Numbers are 13 digits long.

2022-04-22 09:55 UTC, jakesfcoetz commented on src/app/pages/landing-page/landing-page.component.html
> +        <ion-input type="date" value="{{ defaultDate | date: 'dd.MM.yyyy' }}"></ion-input>
Great date picker popup, thank you for the change.
One issue still, when submitting the form, the data object does not display the chosen date.

2022-04-22 09:55 UTC, jakesfcoetz commented on src/app/pages/landing-page/landing-page.component.html
> +          Cell Number should be min 10 chars long.
Please ensure that the validation message corresponds to the validation set on the form. Cell numbers (without country codes) are 10 digits long.

2022-04-22 09:55 UTC, jakesfcoetz commented on src/app/pages/landing-page/landing-page.component.html
> +          <!-- <ion-button class="button button-block button-light" type="reset" color="danger" expand="block" clearInput>Reset Form</ion-button>-->
Please remove all unused code.

2022-04-22 09:55 UTC, jakesfcoetz commented on src/app/pages/landing-page/landing-page.component.ts
> +  get controls(): { [key: string]: AbstractControl } {
This name makes a lot more sense, thank you.
One request though: In your HTML you regularly use the `ionicForm.get("controlName")` method of retrieving a specific control from the form group, while in other circumstances you use the custom `controls()` method. Please standardize on one of these methods as it would greatly improve the readability and reduce possible confusion in the code.

2022-04-22 09:55 UTC, jakesfcoetz commented on src/app/pages/landing-page/landing-page.component.scss
> +.submit-btn {
I presume this class was used in a previous version but is currently unused.

2022-04-22 09:55 UTC, jakesfcoetz commented on src/app/pages/landing-page/landing-page.component.scss
> +ion-list {
A wonderful attempt of adding scroll to your page, but since the `ion-content` tag has been added and contains the scroll functionality, this CSS selector class is no longer needed and can be removed.

2022-04-22 09:55 UTC, jakesfcoetz commented on src/app/pages/landing-page/landing-page.component.html
> +          <ion-button expand="round" type="submit" [disabled]="!ionicForm.valid" color="danger" expand="block">Submit</ion-button>
Please remove duplicate attribute declarations from this button element.

2022-04-22 09:55 UTC, jakesfcoetz commented on src/app/pages/landing-page/landing-page.component.ts
> +  async openToast() {
Since this method is never called, could you elaborate on its purpose? It is also good coding practice to have your constructor as the first method in your class.

2022-04-22 09:55 UTC, jakesfcoetz commented on src/app/pages/landing-page/landing-page.component.ts
> +  defaultDate = '1987-06-30';
This value currently has no direct value in the function of the form and also nullifies the need for validation on the property in the final data object. I would appreciate it if you rethink its usage, especially since the output object's date value does not reflect the chosen date.

2022-04-22 09:55 UTC, jakesfcoetz commented on src/app/pages/landing-page/landing-page.component.ts
> +      email: ['', [, Validators.pattern('[a-z0-9._%+-]+@[a-z0-9.-]+.[a-z]{2,3}$')]],
This email validation pattern is not correctly implemented on the form and I propose using the built-in angular form email validator.

2022-04-22 09:55 UTC, jakesfcoetz commented on src/app/pages/landing-page/landing-page.component.ts
> +  isSubmitted = false;
This variable was used previously but currently has no effect on the flow or display.

2022-04-22 10:32 UTC, tmanmoseri commented on src/app/pages/landing-page/landing-page.component.html
> +  <form [formGroup]="ionicForm" (ngSubmit)="submitForm()" novalidate>
I have removed novalidate attribute since this form values needs to be validated.

2022-04-22 10:34 UTC, tmanmoseri commented on src/app/pages/landing-page/landing-page.component.ts
> +  getDate(event) {
this method was used in previous codes that are now removed. i have also removed it.

2022-04-22 11:25 UTC, tmanmoseri commented on src/app/pages/landing-page/landing-page.component.ts
> +    let date = new Date(event.target.value).toISOString().substring(0, 10);
this method is no longer in use hence i have removed it.

2022-04-22 11:26 UTC, tmanmoseri commented on src/app/pages/landing-page/landing-page.component.ts
> +    let date = new Date(event.target.value).toISOString().substring(0, 10);
i will look into dayjs and its application.

2022-04-22 11:27 UTC, tmanmoseri commented on src/app/pages/landing-page/landing-page.component.html
> +    <form [formGroup]="ionicForm" (ngSubmit)="submitForm()" novalidate>
the novalidate was defined in the beginning of the form definition. since i implemented the form validation, i have then removed it.

2022-04-22 11:43 UTC, tmanmoseri commented on src/app/pages/landing-page/landing-page.component.html
> +        <ion-input type="date" value="{{ defaultDate | date: 'dd.MM.yyyy' }}"></ion-input>
I have put the correct lable and have added a form control name for the date of birth.

2022-04-22 11:47 UTC, tmanmoseri commented on src/app/pages/landing-page/landing-page.component.ts
> +  async openToast() {
I have placed the constructor as the first method. this openToast method was used for the modal button which i will use in the next task. i have removed it as the task is not yet implemented.

2022-04-25 09:07 UTC, tmanmoseri commented on src/app/pages/landing-page/landing-page.component.html
> +                <ion-radio value="mr"></ion-radio>
I have used ion-segment instead.

2022-04-25 09:11 UTC, tmanmoseri commented on src/app/pages/landing-page/landing-page.component.html
> +          <ion-button expand="round" type="submit" [disabled]="!ionicForm.valid" color="danger" expand="block">Submit</ion-button>
a redundant expand attribute removed

2022-04-25 09:17 UTC, tmanmoseri commented on src/app/pages/landing-page/landing-page.component.ts
> +  isSubmitted = false;
the isSubmitted variable has been removed

2022-04-25 09:47 UTC, tmanmoseri commented on src/app/pages/landing-page/landing-page.component.ts
> +  defaultDate = '1987-06-30';
the default date value has been removed for validation efficiency

2022-04-25 11:01 UTC, tmanmoseri commented on src/app/pages/landing-page/landing-page.component.ts
> +      email: ['', [, Validators.pattern('[a-z0-9._%+-]+@[a-z0-9.-]+.[a-z]{2,3}$')]],
I have implemented the correct email validation pattern

2022-04-25 12:14 UTC, tmanmoseri commented on src/app/pages/landing-page/landing-page.component.html
> +              <ion-col>
I used ion-segment instead

2022-04-25 12:38 UTC, tmanmoseri commented on src/app/pages/landing-page/landing-page.component.html
> +          Identification Number should be min 10 chars long.
Please note this radio button id not dynamic. currently it keeps a value that the user select but does not provide the user with an input as per user selection. i will implement that later.

2022-04-25 12:38 UTC, tmanmoseri commented on src/app/pages/landing-page/landing-page.component.html
> +          <ion-col>
i have resorted to ion-segment instead

2022-04-25 12:39 UTC, tmanmoseri commented on src/app/pages/landing-page/landing-page.component.html
> +          <!-- <ion-button class="button button-block button-light" type="reset" color="danger" expand="block" clearInput>Reset Form</ion-button>-->
i have removed unused or commented codes

2022-04-25 12:54 UTC, tmanmoseri commented on src/app/pages/landing-page/landing-page.component.ts
> +  get controls(): { [key: string]: AbstractControl } {
i have resorted to use the custom controls() method consistently

2022-04-25 12:58 UTC, tmanmoseri commented on src/app/pages/landing-page/landing-page.component.scss
> +ion-list {
I have successfully removed it

2022-04-25 12:59 UTC, tmanmoseri commented on src/app/pages/landing-page/landing-page.component.scss
> +.submit-btn {
removed successfully

2022-04-26 09:28 UTC, jakesfcoetz approved these changes
Wonderful @tmanmoseri . Thank you for these changes.

2022-04-26 09:28 UTC, merged